name: 自动构建

on:
  push:
    branches:
      - main # 默认分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: 使用 Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 缓存 NPM 依赖
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: 安装依赖
        run: npm install

      - name: 构建 Hexo 网站
        run: hexo generate # 生成静态网站文件

      - name: 上传 Pages 构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public # 确保 public 目录包含 Hexo 生成的静态文件

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }} # 你的 GitHub Token，确保在 secrets 中设置了 PAT
          publish_dir: ./public # 发布目录，确保是 Hexo 的 public 目录
          external_repository: lxb-blog/lxb-blog.github.io # 目标仓库
          user_name: "github-actions[bot]" # 提交者名字
          user_email: "github-actions[bot]@users.noreply.github.com" # 提交者邮箱
          full_commit_message: "通过 GitHub Actions 部署 Hexo 构建"
          publish_branch: main # 目标仓库的分支，一般是 main
